// RAG Project Presentation Slides
// Auto-generated by PPT Implement Skill

window.slideDataMap = new Map();

// Import all slides
import './slide-1.js';
import './slide-2.js';
import './slide-3.js';
import './slide-4.js';
import './slide-5.js';
import './slide-6.js';
import './slide-7.js';
import './slide-8.js';
import './slide-9.js';
import './slide-10.js';
import './slide-11.js';
import './slide-12.js';
import './slide-13.js';

// Export slide data map
export default window.slideDataMap;
